### ISSUE TITLE
Add Wiki page event.

### ISSUE THREAD

**Issue by BURG3R5** [mdgspace/github-slack-bot#1]
Wiki pages are helpful markdown pages where users can add documentation for their GitHub repository. From the [documentation](https://docs.github.com/en/github-ae@latest/communities/documenting-your-project-with-wikis/about-wikis):

> Every repository on GitHub comes equipped with a section for hosting documentation, called a wiki. You can use your repository's wiki to share long-form content about your project, such as how to use it, how you designed it, or its core principles. A README file quickly tells what your project can do, while you can use a wiki to provide additional documentation.

This issue consists of adding a new event for the bot to track. You'll be updating the bot to make sure that users can be notified when an additional page is added to their Wikis.

These are the steps to do so:

- [ ] Add `WIKI_UPDATED` to `EventType` enum.
- [ ] Add new `WikiPage` model.
- [ ] Add new GitHub parser called `WikiUpdateEventParser`.
- [ ] Add new `elif` clause to `compose_message` for `WIKI_UPDATED` event.

**More information can be found in the individual issues. Leave a comment if you have any doubts.**
