### ISSUE TITLE
Add label activity event.

### ISSUE THREAD

**Issue by BURG3R5** [mdgspace/github-slack-bot#6]
Labels are helpful tags which users can use to sort and manage issues/PRs for their GitHub repository. From the [documentation](https://docs.github.com/en/github-ae@latest/issues/using-labels-and-milestones-to-track-work/managing-labels):

> You can manage your work on GitHub by creating labels to categorize issues and pull requests. You can apply labels in the repository the label was created in. Once a label exists, you can use the label on any issue or pull request within that repository.

This issue consists of adding a new event for the bot to track. You'll be updating the bot to make sure that users can be notified when labels are added/modified/deleted in their repository.

These are the steps to do so:

- [ ]  Add `LABEL_UPDATED` to `EventType` enum.
- [ ] Add new `Label` model.
- [ ] Add new GitHub parser called `LabelUpdateEventParser`.
- [ ] Add new `elif` clause to `compose_message` for `LABEL_UPDATED` event.

**More information can be found in the individual issues.
Leave a comment if you have any doubts.**
